version: "3.3"
services:
  mysql-container:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=plaweb
      - MYSQL_USER=pla
      - MYSQL_PASSWORD=1
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
    image: plaweb:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql-container

volumes:
  mysql_data: