server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: 'jdbc:mysql://localhost:3306/plaweb'
    username: root
    password: rootroot
    # url: 'jdbc:mysql://mysql-container:3306/plaweb'
    # username: pla
    # password: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB